name: vbjax-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  # Build tools
  - cmake
  - emscripten_emscripten-wasm32==3.1.73
  - pip
  - python=3.11
  - yarn
  - click
  # Build dependencies from pyproject.toml
  - hatchling
  - setuptools>=45
  - setuptools_scm
  # Core dependencies that should work in emscripten
  - numpy
  - scipy