"""
Show a few examples from the path data set generated by pathgen module.

"""

def main():
    import numpy as np
    import pylab as pl

    ims = np.load('ims.npy')
    masks = np.load('masks.npy')

    im0 = ims[masks]
    im1 = ims[~masks

    px = im0.shape[1]
    print('image size', im0.shape)

    nwide = 8
    ntall = 8
    im0 = im0[:nwide*ntall].reshape(ntall, nwide, px, px).transpose(
        0, 2, 1, 3).reshape(ntall*px, nwide*px)
    im1 = im1[:nwide*ntall].reshape(ntall, nwide, px, px).transpose(
        0, 2, 1, 3).reshape(ntall*px, nwide*px)

    pl.figure(figsize=(20, 10), dpi=150)
    pl.subplot(121)
    pl.imshow(im0, cmap='binary')
    pl.subplot(122)
    pl.imshow(im1, cmap='binary')
    pl.savefig('paths.png')


if __name__ == "__main__":
    main()
