name: Build for Emscripten-Forge

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.5-0'
        environment-file: environment-wasm-build.yml
        cache-environment: true
        
    - name: Create recipe directory
      run: |
        mkdir -p recipe
        
    - name: Generate conda recipe
      shell: micromamba-shell {0}
      run: |
        cat > recipe/recipe.yaml << EOF
        context:
          version: ${{ github.ref_type == 'tag' && github.ref_name || '0.0.17' }}
          
        package:
          name: vbjax
          version: \${{ version }}
          
        source:
          path: ..
          
        build:
          number: 0
          noarch: python
          script: |
            # Create a minimal setup that can be imported without JAX
            python -m pip install . --no-deps -vv
          
        requirements:
          host:
            - python >=3.7
            - pip
            - hatchling
            - setuptools>=45
            - setuptools_scm
          run:
            - python >=3.7
            - numpy
            - scipy
            # Note: JAX/JAXlib are not included as they may not be fully
            # compatible with emscripten environments yet. This build
            # creates the package structure but functionality may be limited.
            
        test:
          imports:
            # Skip the main vbjax import test as it requires JAX
            # - vbjax
          commands:
            # Test basic package structure
            - python -c "import vbjax._version; print('vbjax version file available')"
            
        about:
          home: https://github.com/ins-amu/vbjax
          license: Apache-2.0
          license_file: LICENSE
          summary: Virtual brains w/ JAX (WebAssembly build - limited functionality)
          description: |
            vbjax is a Jax-based package for working with virtual brain style models.
            This is a WebAssembly build with limited functionality due to JAX
            compatibility constraints in emscripten environments.
          dev_url: https://github.com/ins-amu/vbjax
          
        extra:
          recipe-maintainers:
            - ins-amu
        EOF
        
    - name: Build package with rattler-build
      shell: micromamba-shell {0}
      run: |
        # Install rattler-build
        micromamba install rattler-build -c conda-forge -y
        
        # Build for emscripten-wasm32 platform
        rattler-build build \
          --recipe recipe/recipe.yaml \
          --target-platform=emscripten-wasm32 \
          -c https://repo.prefix.dev/emscripten-forge-dev \
          -c conda-forge \
          --output-dir ./output
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: emscripten-build-artifacts
        path: |
          ./output/**/*.tar.bz2
          ./output/**/*.conda
          
    - name: List build outputs
      run: |
        echo "Build completed successfully!"
        find ./output -name "*.tar.bz2" -o -name "*.conda" | head -10
        echo ""
        echo "Note: This WebAssembly build has limited functionality due to JAX compatibility constraints."