name: PyInstaller builds

on:
  push:
    branches: [ main, cli-entry-pyinstaller ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    name: Build PyInstaller single-file executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build single-file executable
        run: |
          # Create a dist directory for pyinstaller
          pyinstaller --onefile --name vbjax vbjax/__main__.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vbjax-cli-${{ matrix.os }}
          path: dist/

  attach-release:
    name: Attach artifacts to release (when release event)
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts

      - name: Create release assets
        uses: softprops/turnstyle@v1
        with:
          artifacts: 'build-artifacts/**/dist/**'
