name: run pytests

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: setup python
        run: sudo apt-get update && sudo apt-get install -y python3-{pip,numpy,scipy}

      - name: install jax
        run: pip install jax jaxlib pytest

      - name: run tests
        run: pytest
