name: run pytests

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: build docker image
        run: docker build -t nfjax -f Dockerfile

      - name: run tests in container
        run: docker run --rm -v $PWD:/work -w /work nfjax pytest
